apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: calendar-application
spec:
  selector:
    app: calendar-back
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
    # port: 443
    # targetPort: 443
    # nodePort: 30001