apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: calendar-application
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 33022