name: workflow production deploy frontend
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy prod frontend'
        required: true
        default: 'latest'
jobs:
  prod-deploy:
    environment: production
    runs-on: ubuntu-latest
    container:
      image:  kevinpsirius/pipeline_deployment_image:calendar
#      options: --cpus 0.20
      env:
        sshKey: ${{ secrets.SSH_KEY }}
    steps:
      - name: Generate new build for production
        run: |
          cd /var/www/html && git clone https://github.com/kevP-Sirius/2itecheval2.git
          cd /var/www/html/2itecheval2/calendar_frontend && npm ci && npm run build
      - name: Generate SSH connection to server with ansible for production
        run: |
          touch /var/www/html/mypckey.pem &&  chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd /var/www/html/playbook && ansible-playbook playbook/deploy-prod-calendar-front.yml -e "ansible_ssh_timeout=180"
