apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-client-service
  namespace: calendar-application
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - showtime-app.click
    secretName: ingress-secret
  rules:
  - host: showtime-app.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-client-service
            port:
              number: 80
  
      